import type { Tab } from "./admin-types";

export const ADMIN_TABS: Tab[] = [
  "analytics",
  "reports",
  "assistant",
  "realtime",
  "behavior",
  "appearance",
  "posters",
  "ai-upload",
  "ai-settings",
  "assistant-requests",
  "categories",
  "subcategories",
  "display-order",
  "orders",
  "customers",
  "abandoned",
  "custom",
  "offers",
  "photo-4x6",
  "photo-printing-media",
  "post-order",
  "slider",
  "hero-banners",
  "highlights",
  "best-sellers",
  "sections",
  "home-categories",
  "room-transformation",
  "sets",
  "collections",
  "collection-showcase",
  "quickbar",
  "footer-menu",
  "mockups",
  "wishlists",
  "reviews",
  "before-after",
  "photo-enhancement",
  "storefront-content",
  "marketing",
  "catalog",
  "campaign-landings",
  "campaign-report",
  "social-proof",
  "announcement",
  "size-guide",
  "alerts",
  "notifications",
  "error-logs",
  "performance",
  "stability",
  "images",
  "backups",
  "system-health",
  "env-check",
  "maintenance",
  "exports",
  "branding",
  "settings",
];

export const NAVIGATION_GROUPS = {
  core: [
    "analytics",
    "realtime",
    "orders",
    "customers",
    "categories",
    "display-order",
    "abandoned",
    "behavior",
  ],
  marketing: [
    "catalog",
    "offers",
    "campaign-landings",
    "campaign-report",
    "social-proof",
    "reviews",
    "marketing",
    "announcement",
  ],
  content: [
    "posters",
    "hero-banners",
    "highlights",
    "best-sellers",
    "sections",
    "home-categories",
    "room-transformation",
    "sets",
    "collections",
    "collection-showcase",
    "custom",
    "before-after",
    "storefront-content",
    "size-guide",
    "photo-4x6",
    "photo-printing-media",
    "slider",
  ],
  operations: ["post-order", "notifications", "alerts", "quickbar", "footer-menu"],
  system: [
    "system-health",
    "performance",
    "stability",
    "error-logs",
    "env-check",
    "maintenance",
    "backups",
    "exports",
    "images",
    "settings",
  ],
  ai: ["ai-upload", "ai-settings", "assistant", "assistant-requests"],
  appearance: ["appearance", "branding"],
  more: ["reports", "subcategories", "mockups", "wishlists", "photo-enhancement"],
};

export function isAdminTab(value: string): value is Tab {
  return (ADMIN_TABS as string[]).includes(value);
}

export function getGroupForTab(tabKey: string): keyof typeof NAVIGATION_GROUPS | null {
  for (const [group, tabs] of Object.entries(NAVIGATION_GROUPS)) {
    if ((tabs as readonly string[]).includes(tabKey))
      return group as keyof typeof NAVIGATION_GROUPS;
  }
  return null;
}
